### ISSUE TITLE
Deficient implementation

### ISSUE THREAD

**Issue by kgryte** [remko/lcg-random#1]
A few comments:
1. The `increment` option cannot be set to `0`. Thus, generating a Lehmer RNG is not possible.
2. Supposing the `increment` could be `0`, the seed should not be allowed to be `0`. This is obvious based on congruence relation. If both are zero, the state is also **always** `0`.
3. As stated in the GSL source,
   
   > The `rand()` generator is not very good -- the low bits of successive numbers are correlated.

While the spirit of the implementation is good (i.e., the ability to create an LCG), the implementation makes it too easy for users to create (and thus use) a bad PRNG.

**Comment by remko** [comment]
Thanks a lot for pointing this out, @kgryte. 

I'll push a fix for (1) later today, and add some bounds checks that cover (2).

Do you have a suggestion for a better default for (3)? I realized that GSL's `rand` wasn't very good, but it wasn't as important to me where I needed `lcg-random` (the predictability was).

**Comment by kgryte** [comment]
@remko Yes, a better choice would, at minimum, be Park's and Miller's LCG, also known as MINSTD.

**Comment by remko** [comment]
@kgryte Great, I wanted to double check that (because it also got some critique, and I wasn't sure how important that was). Thanks for clarifying that!
